{% extends "../../../common/Dockerfile.j2" %}
{% block additional_packages %}patchelf python3 gdb binutils util-linux{% endblock %}
{% block after_setup %}
RUN set -eux; \
    binary="$(find /challenge -maxdepth 1 -type f -perm /111 ! -name '.*' | sort | head -n1)"; \
    chmod 4755 "$binary"; \
    patchelf --set-interpreter /challenge/lib/ld-linux-x86-64.so.2 --set-rpath /challenge/lib "$binary"; \
    chmod u-s /challenge/lib/libc.so.6 /challenge/lib/ld-linux-x86-64.so.2
{% endblock %}
