{% extends "../../../../common/Dockerfile.j2" %}
{% block additional_packages %}gcc binutils{% endblock %}
{% block before_copy %}RUN echo race-level-4-1-v1 > /etc/pwn_race_level{% endblock %}
{% block setup %}
RUN <<END
    set -e
    mkdir -p /home/hacker
    chown 1000:1000 /home/hacker
    gcc -O0 -fno-pie -no-pie -fno-stack-protector -o /challenge/babyrace_level4_1 /challenge/babyrace_level4_1.c
    chmod 4755 /challenge/babyrace_level4_1
    rm -f /challenge/Dockerfile /challenge/babyrace_level4_1.c
END
{% endblock %}
