{% extends "../../../../common/Dockerfile.j2" %}
{% block additional_packages %}gcc{% endblock %}
{% block before_copy %}RUN echo race-level-3-1-v1 > /etc/pwn_race_level{% endblock %}
{% block setup %}
RUN <<END
    set -e
    mkdir -p /home/hacker
    chown 1000:1000 /home/hacker
    gcc -O0 -fno-pie -no-pie -o /challenge/babyrace_level3_1 /challenge/babyrace_level3_1.c
    chmod 4755 /challenge/babyrace_level3_1
    rm -f /challenge/Dockerfile /challenge/babyrace_level3_1.c
END
{% endblock %}
