{% extends "../../../../common/Dockerfile.j2" %}
{% block additional_packages %}gcc binutils{% endblock %}
{% block before_copy %}RUN echo sandbox-level-2-v3 > /etc/pwn_sandbox_level{% endblock %}
{% block setup %}
RUN <<END
    set -e
    gcc -O0 -fno-pie -no-pie -o /challenge/babyjail_level2 /challenge/babyjail_level2.c
    chmod 4755 /challenge/babyjail_level2
    rm -f /challenge/Dockerfile /challenge/.setup /challenge/babyjail_level2.c
END
{% endblock %}
